spring.data.mongodb.uri=mongodb+srv://sg:guptashulbhi@cluster0.ummlqpx.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=aiInterviewCoach
server.port=8080

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash