spring.data.mongodb.uri=mongodb+srv://shulbhi18_db_user:IispPflT7zSwu8iF@cluster0.gfe2hcm.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=aiInterviewCoach
server.port=8080

gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash

mongodb+srv://sg:guptashulbhi@cluster0.ummlqpx.mongodb.net/?appName=Cluster0